#!/bin/bash
echo install basic linux packages
(
main() {
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    apt-get update

    apt-get install -y locales
    sed -i -r 's/^\s*#\s*en_US\.UTF-8\s+UTF-8\s*$/en_US.UTF-8 UTF-8/g' /etc/locale.gen
    locale-gen

    apt-get install -y \
        coreutils \
        apt-transport-https \
        ca-certificates \
        gnupg2 \
        software-properties-common \
        rsync \
        redir \
        autossh \
        bash \
        bash-completion \
        make \
        jq \
        openssh-client \
        tar \
        curl \
        net-tools \
        dnsutils \
        vim \
        procps \
        htop \
        iotop \
        time \
        expect \
        netcat-openbsd \
        git \
        ftp \
        ncftp \
        tmux \
        tmate \
        build-essential \
        xz-utils

    local s6_version=v3.1.6.2
    curl -fsSL "https://github.com/just-containers/s6-overlay/releases/download/$s6_version/s6-overlay-noarch.tar.xz" \
        | tar -Jxpf - -C /
    curl -fsSL "https://github.com/just-containers/s6-overlay/releases/download/$s6_version/s6-overlay-$(uname -m).tar.xz" \
        | tar -Jxpf - -C /
}
main
)
