#!/bin/bash
echo install base python runtime
(
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    apt-get update

    apt-get install -y python3-setuptools

    command -v pip3 || apt-get install -y python3-pip

    ln -s "$(command -v pip3)" "$(dirname "$(command -v pip3)")/pip"

    pip install -U \
        pip \
        pipenv

    apt-get install -y \
        libsqlite3-dev \
        \
        python3-dev \
        zlib1g-dev \
        zlib1g \
        gzip \
        \
        libbz2-dev \
        bzip2 \
        \
        libreadline-dev \
        \
        openssl \
        libssl-dev \
        python3-openssl \
        \
        build-essential
)
