#!/bin/bash
echo install base python runtime
(
main() {
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    apt-get update

    apt-get install -y python3-setuptools

    command -v pip || apt-get install -y python3-pip

    pip install --break-system-packages -U \
        pip \
        pipenv

    apt-get install -y \
        libsqlite3-dev \
        \
        libffi8 \
        libffi-dev \
        liblzma-dev \
        \
        python3-dev \
        zlib1g-dev \
        zlib1g \
        gzip \
        \
        libbz2-dev \
        bzip2 \
        \
        libreadline-dev \
        \
        openssl \
        libssl-dev \
        python3-openssl \
        \
        build-essential
}
main
)
