#!/bin/bash
echo install asdf
(
main() {
    set -exo pipefail

    sudo -u vagrant bash <<'EOF'
    main() {
        set -eo pipefail ; . ~/.bashrc ; . /etc/provision_functions ; set -x

        local version="v0.14.0"

        mkdir -p "$HOME/.local/asdf.data"
        git clone https://github.com/asdf-vm/asdf.git "$HOME/.local/asdf" --branch "$version"

        [[ "$(cd "$HOME/.local/asdf" && git log -1 --format="%H")" == "ccdd47df9b73d0a22235eb06ad4c48eb57360832" ]] || ( >&2 echo "signature mismatch" && exit 1 )

        bashrc_add_noninteractive <<'BASHRC_EOF'
export ASDF_DIR="$HOME/.local/asdf"
export ASDF_DATA_DIR="$HOME/.local/asdf.data"
. "$ASDF_DIR/asdf.sh"
BASHRC_EOF

        bashrc_add_interactive <<'BASHRC_EOF'
. "$ASDF_DIR/completions/asdf.bash"
BASHRC_EOF

        asdf version
    }
    main

EOF

}
main
)
