#!/bin/bash
echo install yarn npm package
(
main() {
    set -exo pipefail

    sudo -u vagrant bash <<'EOF'
    main() {
        set -eo pipefail ; . ~/.bashrc ; set -x

        local latest_version="v1.22.19"
        # latest_version="latest"
        npm install -g "yarn@$latest_version"
    }
    main

EOF

}
main
)
