#!/bin/bash
echo install yarn npm package
(
main() {
    set -exo pipefail

    sudo -u vagrant bash <<'EOF'
    main() {
        set -eo pipefail ; . ~/.bashrc ; set -x

        corepack enable
        asdf reshim

        yarn --version
    }
    main

EOF

}
main
)
