#!/bin/bash
echo install rust
(
main() {
    set -exo pipefail

    sudo -u vagrant bash <<'EOF'
    main() {
        set -eo pipefail ; . /etc/provision_functions ; set -x

        bashrc_add_noninteractive <<'BASHRC_EOF'
export CARGO_HOME="$HOME/.cargo"
BASHRC_EOF

        curl -fsSL https://sh.rustup.rs | sh -s -- -y --no-modify-path

        bashrc_add_noninteractive <<'BASHRC_EOF'
export PATH="$CARGO_HOME/bin:$PATH"
BASHRC_EOF

        bashrc_add_interactive <<'BASHRC_EOF'
eval "$(rustup completions bash)"
BASHRC_EOF
    }
    main

EOF

}
main
)
