#!/bin/bash
echo install rust
(
main() {
    set -exo pipefail

    sudo -u vagrant bash <<'EOF'
    main() {
        set -eo pipefail ; . ~/.bashrc ; . /etc/provision_functions ; set -x

        local version="1.77.0"

        asdf plugin add rust
        asdf install rust "$version"
        asdf global rust "$version"

        bashrc_add_noninteractive < <(printf 'export PATH="$PATH:$ASDF_DATA_DIR/installs/rust/%s/bin"\n' "$version")

        bashrc_add_interactive <<'BASHRC_EOF'
eval "$(rustup completions bash)"
BASHRC_EOF

        rustc --version
    }
    main

EOF

}
main
)
