#!/bin/bash
echo install yamllint from https://github.com/adrienverge/yamllint
(
main() {
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    apt-get install -y \
        libyaml-dev

    local version='==1.28.0'
    # version=''

    pip install "yamllint${version}"
}
main
)
