#!/bin/bash
echo install yamllint from https://github.com/adrienverge/yamllint
(
main() {
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    # already installed
    # apt-get install -y \
    #     libyaml-dev

    local version='==1.35.1'
    # version=''

    pip install --break-system-packages "yamllint${version}"
}
main
)
