#!/bin/bash
echo install cfn-lint from https://github.com/awslabs/cfn-python-lint
(
main() {
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    apt-get install -y \
        libyaml-dev

    local version='==0.65.0'
    # version=''

    pip install "cfn-lint${version}"
}
main
)
