#!/bin/bash
echo install cfn-lint from https://github.com/awslabs/cfn-python-lint
(
main() {
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    # already installed
    # apt-get install -y \
    #     libyaml-dev

    local version='==0.86.1'
    # version=''

    pip install  --break-system-packages "cfn-lint${version}"
}
main
)
