#!/bin/bash
echo install jsonlint from nodejs packages
(
main() {
    set -exo pipefail

    sudo -u vagrant bash <<'EOF'
    main() {
        set -eo pipefail ; . ~/.bashrc ; set -x

        local version='v1.6.3'
        # version='latest'

        npm install -g "jsonlint@${version}"
    }
    main

EOF

}
main
)
