#!/bin/bash
echo install java version manager
(
main() {
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    apt-get update

    # next line is a required hack due to manpage moving elsewhere
    # Ref: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863199
    mkdir -p /usr/share/man/man1

    local major_version='17'
    apt-get install -y \
        man-db \
        "openjdk-$major_version-jre-headless" \
        "openjdk-$major_version-jdk"

    sudo -u vagrant bash <<'EOF'
    main() {
        set -eo pipefail ; . ~/.bashrc ; . /etc/provision_functions ; set -x

        export JENV_DIR="$HOME/.jenv"

        git clone https://github.com/gcuisinier/jenv.git "$JENV_DIR"

        cd "$JENV_DIR"
        git fetch origin

        local latest_jenv_release=0.5.7
        # latest_jenv_release="$(cd "$JENV_DIR" ; git fetch origin ; git describe --abbrev=0 --tags --match "[0-9]*" $(git rev-list --tags --max-count=1))"

        git checkout -f "$latest_jenv_release"
        [[ "$(git log -1 --format="%H")" = "1032e0036da40f720766e563d766272699a420f7" ]] || ( >&2 echo "signature mismatch" && exit 1 )

        bashrc_add_noninteractive <<'BASHRC_EOF'
export JENV_DIR="$HOME/.jenv"
export PATH="$JENV_DIR/bin:$PATH"
eval "$(jenv init -)"
BASHRC_EOF

        # jenv is noisy as hell with set -x enabled
        # disabling it so people can remain sane
        set +x

        jenv rehash
    }
    main

EOF

}
main
)
