#!/bin/bash
echo install mysql client
(
main() {
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    apt-get update

    apt-get install -y \
        redis-tools

    redis-cli --version
}
main
)
