#!/bin/bash
echo install nginx
(
main() {
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    apt-get update

    local version="1.14.2"
    # repo_version="=$(apt-cache madison nginx | grep -E '^\s*nginx\s*\|\s*'"$(sed -E 's/\./\\./' <<<"$version")" | sed -E 's/^[^\|]+\|\s*([^\|]+)\|.*$/\1/ ; s/\s+$//' | sort -u)"

    # looks like available repo version changes all the time, so not going to try and pin a specific revision anymore
    local repo_version=""

    apt-get install -y \
        "nginx$repo_version"
}
main
)
