#!/bin/bash
echo install adr tools
(

    # install bash completion for docker-compose
    sudo -u vagrant bash <<'EOF'
        set -eo pipefail ; . /etc/provision_functions ; set -x

        mkdir "$HOME/.adr-tools"

        version="3.0.0"
        curl -fsSL https://github.com/npryce/adr-tools/archive/$version.tar.gz | tar zxf - -C "$HOME/.adr-tools" --transform 's/^adr-tools-//'

        bashrc_add_noninteractive <<BASHRC_EOF
export PATH="\$PATH:\$HOME/.adr-tools/$version/src"
BASHRC_EOF

EOF
)
