#!/bin/bash
echo install go version manager
(
main() {
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    apt-get update

    apt-get install -y \
        bison

    sudo -u vagrant bash <<'EOF'
    main() {
        set -eo pipefail ; . /etc/provision_functions ; set -x

        curl -fsSL https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer | bash

        bashrc_add_noninteractive <<'BASHRC_EOF'
. "$HOME/.gvm/scripts/gvm"
BASHRC_EOF

        local latest_binary_release="go1.19"

        # major_version=1
        # latest_binary_release="go$(set -eo pipefail ; gvm listall | grep -E '^\s*go'"$major_version"'\.[0-9]+(\.[0-9]+)?\s*$' | sed -E 's/^\s*go([^\s]+)\s*/\1/' | sort --version-sort | tail -1)"

        printf 'latest_binary_release=%q\n' "$latest_binary_release"
        gvm install "$latest_binary_release" -B
        gvm use "$latest_binary_release" --default

        local latest_release="go1.19"

        if [ "$latest_binary_release" != "$latest_release" ]; then
            printf 'latest_release=%q\n' "$latest_release"
            gvm install "$latest_release"
            gvm use "$latest_release" --default
        fi
    }
    main

EOF

}
main
)
