#!/bin/bash
echo install go version manager
(
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    sudo -u vagrant bash <<'EOF'

        set -eo pipefail ; . ~/.bashrc ; set -x

        latest_version="v1.11.0"
        srcdir="$HOME/.mage_src"

        install -m0700 -d "$srcdir"
        cd "$srcdir"
        git clone --depth=1 --branch "$latest_version" https://github.com/magefile/mage .
        go run bootstrap.go


EOF
)
