#!/bin/bash
echo install go version manager
(
main() {
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    sudo -u vagrant bash <<'EOF'
    main() {
        set -eo pipefail ; . ~/.bashrc ; set -x

        local latest_version="v1.13.0"
        local srcdir="$HOME/.mage_src"

        install -m0700 -d "$srcdir"
        cd "$srcdir"
        git clone --depth=1 --branch "$latest_version" https://github.com/magefile/mage .
        go run bootstrap.go
    }
    main

EOF

}
main
)
