#!/bin/bash
echo install go version manager
(
main() {
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    sudo -u vagrant bash <<'EOF'
    main() {
        set -eo pipefail ; . ~/.bashrc ; . /etc/provision_functions ; set -x

        local version="1.57.1"

        asdf plugin add golangci-lint
        asdf install golangci-lint "$version"
        asdf global golangci-lint "$version"

        golangci-lint version
    }
    main

EOF

}
main
)
