#!/bin/bash
echo install yq
(
main() {
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    sudo -u vagrant bash <<'EOF'
    main() {
        set -eo pipefail ; . ~/.bashrc ; . /etc/provision_functions ; set -x

        local version="4.43.1"

        asdf plugin add yq
        asdf install yq "$version"
        asdf global yq "$version"

        yq --version
    }
    main

EOF

}
main
)
