#!/bin/bash
echo install jless
(
main() {
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    apt-get update

    # install dynamically linked dependencies
    apt-get install -y \
        libxcb1-dev \
        libxcb-render0-dev \
        libxcb-shape0-dev \
        libxcb-xfixes0-dev

    sudo -u vagrant bash <<'EOF'
    main() {
        set -eo pipefail ; . ~/.bashrc ; . /etc/provision_functions ; set -x

        local version='v0.9.0'

        git clone "https://github.com/PaulJuliusMartinez/jless.git" /tmp/jless.git --branch "$version" --single-branch

        [[ "$(cd /tmp/jless.git && git log -1 --format="%H")" == "21dd6100edb47145bb9570931bec29697bcd0d9b" ]] || ( >&2 echo "signature mismatch" && exit 1 )

        cargo install --path /tmp/jless.git
        rm -rf /tmp/jless.git

        jless --version

        bashrc_add_noninteractive <<'BASHRC_EOF'
alias yless='\jless --yaml'
BASHRC_EOF

    }
    main

EOF

}
main
)
