#!/bin/bash
echo install ytt
(
main() {
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    sudo -u vagrant bash <<'EOF'
    main() {
        set -eo pipefail ; . ~/.bashrc ; . /etc/provision_functions ; set -x

        local version="0.48.0"

        asdf plugin add ytt
        asdf install ytt "$version"
        asdf global ytt "$version"

        ytt --version
    }
    main

EOF

}
main
)
