#!/bin/bash
echo install yq
(
main() {
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    sudo -u vagrant bash <<'EOF'
    main() {
        set -eo pipefail ; . ~/.bashrc ; . /etc/provision_functions ; set -x

        local version="1.9.9"

        asdf plugin add sbt
        asdf install sbt "$version"
        asdf global sbt "$version"

        sbt --version
    }
    main

EOF

}
main
)
