#!/bin/bash
echo install zig
(
main() {
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    sudo -u vagrant bash <<'EOF'
    main() {
        set -eo pipefail ; . ~/.bashrc ; . /etc/provision_functions ; set -x

        # latest stable release:
        # https://github.com/ziglang/zig/releases

        local version="0.13.0"

        local arch="$(uname -m)"
        local sig="d45312e61ebcc48032b77bc4cf7fd6915c11fa16e4aad116b66c9468211230ea"
        if [[ "$arch" == "aarch64" ]]; then
            sig="041ac42323837eb5624068acd8b00cd5777dac4cf91179e8dad7a7e90dd0c556"
        fi

        local bundle="zig-linux-$arch-$version"
        local fname="$bundle.tar.xz"
        local url="https://ziglang.org/download/$version/$fname"

        mkdir /tmp/zig-bundle
        cd /tmp/zig-bundle
        curl -fsSL "$url" -o "$fname"
        sha256sum -c <(printf '%s' "$sig $fname")

        tar xf "$fname"

        printf '%s' "$version" > "$bundle/version.txt"
        mv "$bundle" "$HOME/.local/zig"

        cd /
        rm -rf /tmp/zig-bundle

        ln -s "$HOME/.local/zig/zig" "$HOME/.local/bin/zig"
        "$HOME/.local/bin/zig" version
    }
    main

EOF

}
main
)
