#!/bin/bash
echo install zig
(
main() {
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    sudo -u vagrant bash <<'EOF'
    main() {
        set -eo pipefail ; . ~/.bashrc ; . /etc/provision_functions ; set -x

        # latest stable release:
        # https://github.com/ziglang/zig/releases

        local version="0.11.0"

        local arch="$(uname -m)"
        local sig="2d00e789fec4f71790a6e7bf83ff91d564943c5ee843c5fd966efc474b423047"
        if [[ "$arch" == "aarch64" ]]; then
            sig="956eb095d8ba44ac6ebd27f7c9956e47d92937c103bf754745d0a39cdaa5d4c6"
        fi

        local bundle="zig-linux-$arch-$version"
        local fname="$bundle.tar.xz"
        local url="https://ziglang.org/builds/$fname"

        mkdir /tmp/zig-bundle
        cd /tmp/zig-bundle
        curl -fsSL "$url" -o "$fname"
        sha256sum -c <(printf '%s' "$sig $fname")

        tar xf "$fname"

        printf '%s' "$version" > "$bundle/version.txt"
        mv "$bundle" "$HOME/.local/zig"

        cd /
        rm -rf /tmp/zig-bundle

        ln -s "$HOME/.local/zig/zig" "$HOME/.local/bin/zig"
        "$HOME/.local/bin/zig" version
    }
    main

EOF

}
main
)
