#!/bin/bash
echo install ivy apl and gnu apl
(
main() {
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    sudo -u vagrant bash <<'EOF'
    main() {
        set -eo pipefail ; . ~/.bashrc ; . /etc/provision_functions ; set -x

        local version="0.3.4"

        go install robpike.io/ivy@v$version

        [[ "$( ivy <(printf '1+2') )" = "3" ]] || (>&2 echo something went wrong ; exit 1)

        go clean -cache

        # TODO: install gnu apl
    }
    main

EOF

}
main
)
