#!/bin/bash
echo install ivy apl and uiua apl
(
main() {
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    sudo -u vagrant bash <<'EOF'
    main() {
        set -eo pipefail ; . ~/.bashrc ; . /etc/provision_functions ; set -x

        local version="0.3.4"

        go install robpike.io/ivy@v$version

        [[ "$( ivy <(printf '1+2') )" == "3" ]] || (>&2 echo something went wrong ; exit 1)

        go clean -cache

        #########

        # latest release:
        # https://github.com/uiua-lang/uiua/releases

        local version='0.9.5'

        git clone "https://github.com/uiua-lang/uiua.git" "/tmp/uiua.git" --branch "$version" --single-branch

        [[ "$(cd "/tmp/uiua.git" && git log -1 --format="%H")" == "dff0cb712f452c6ade4d1f3606475d1565fa3c8c" ]] || ( >&2 echo "signature mismatch" && exit 1 )

        cargo install --path "/tmp/uiua.git"
        rm -rf "/tmp/uiua.git"

        uiua --version
    }
    main

EOF

}
main
)
