#!/bin/bash
echo install fzf
(
main() {
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    sudo -u vagrant bash <<'EOF'
    main() {
        set -eo pipefail ; . ~/.bashrc ; . /etc/provision_functions ; set -x

        local version="0.48.1"

        asdf plugin add fzf
        asdf install fzf $version
        asdf global fzf $version

        fzf --version
    }
    main

EOF

}
main
)
