#!/bin/bash
echo install just
(
main() {
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    sudo -u vagrant bash <<'EOF'
    main() {
        set -eo pipefail ; . ~/.bashrc ; . /etc/provision_functions ; set -x

        local version="1.25.2"

        asdf plugin add just
        asdf install just $version
        asdf global just $version

        just --version
    }
    main

EOF

}
main
)
