#!/bin/bash
echo install earthly
(
main() {
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    sudo -u vagrant bash <<'EOF'
    main() {
        set -eo pipefail ; . ~/.bashrc ; . /etc/provision_functions ; set -x

        local version="0.8.6"

        asdf plugin add earthly
        asdf install earthly $version
        asdf global earthly $version

        earthly --version
    }
    main

EOF

}
main
)
