#!/bin/bash
echo install jsonnet
(
main() {
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    sudo -u vagrant bash <<'EOF'
    main() {
        set -eo pipefail ; . ~/.bashrc ; . /etc/provision_functions ; set -x

        # latest release:
        # https://github.com/google/go-jsonnet/releases

        local version="0.20.0"

        local cpuarch="x86_64"
        if [[ "$(uname -m)" == "aarch64" ]]; then
            cpuarch="arm64"
        fi

        local bundle="go-jsonnet_${version}_Linux_$cpuarch"
        local fname="$bundle.tar.gz"
        local url="https://github.com/google/go-jsonnet/releases/download/v$version/$fname"

        mkdir /tmp/jsonnet-bundle
        cd /tmp/jsonnet-bundle
        curl -fsSL "$url" -o "$fname"
        sha256sum -c <(printf "49fbc99c91dcd2be53fa856307de3b8708c91dc5c74740714fdf9317957322e0 $fname")

        mkdir "$bundle"
        tar xf "$fname" -C "$bundle"
        mv "$bundle" "$HOME/.local/jsonnet"

        ln -s "$HOME/.local/jsonnet/jsonnet" "$HOME/.local/bin/jsonnet"
        ln -s "$HOME/.local/jsonnet/jsonnet-deps" "$HOME/.local/bin/jsonnet-deps"
        ln -s "$HOME/.local/jsonnet/jsonnet-lint" "$HOME/.local/bin/jsonnet-lint"
        ln -s "$HOME/.local/jsonnet/jsonnetfmt" "$HOME/.local/bin/jsonnetfmt"

        cd /
        rm -rf cd /tmp/jsonnet-bundle

        "$HOME/.local/jsonnet/jsonnet" --version
    }
    main

EOF

}
main
)
