#!/bin/bash
echo install cntlm
(
main() {
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    sudo -u vagrant bash <<'EOF'
    main() {
        set -eo pipefail ; . ~/.bashrc ; . /etc/provision_functions ; set -x

        # a simple corporate proxy
        #
        # https://sourceforge.net/projects/cntlm/
        #
        # https://github.com/versat/cntlm

        local version="0.92.3"

        local bundle="cntlm-$version"
        local fname="$bundle.tar.gz"
        local url="https://downloads.sourceforge.net/project/cntlm/cntlm/cntlm%20$version/$fname"

        mkdir /tmp/cntlm-tar-src
        cd /tmp/cntlm-tar-src
        curl -fsSL "$url" -o "$fname"
        sha256sum -c <(printf '%s' "9c3ad10924d43f7248df9ecd33cbc033afbd7ea8d9545de0d68a2782fed76298 $fname")

        tar xf "$fname"

        cd "$bundle"
        ./configure
        make prefix=''
        make prefix='' DESTDIR="$HOME/.local/cntlm" install

        cd /
        rm -rf /tmp/cntlm-tar-src

        ln -s "$HOME/.local/cntlm/usr/sbin/cntlm" "$HOME/.local/bin/cntlm"

        test -s "$HOME/.local/bin/cntlm"
        test -x "$HOME/.local/bin/cntlm"
        test -s "$HOME/.local/cntlm/usr/sbin/cntlm"
        test -x "$HOME/.local/cntlm/usr/sbin/cntlm"

        # man $HOME/.local/cntlm/usr/share/man/man1/cntlm.1
    }
    main

EOF

}
main
)
