#!/bin/bash
echo install julia
(
main() {
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    sudo -u vagrant bash <<'EOF'
    main() {
        set -eo pipefail ; . ~/.bashrc ; . /etc/provision_functions ; set -x

        #
        # https://julialang.org/
        #

        # latest LTS and stable:
        # https://julialang.org/downloads/

        # LTS as of 2024-04-04 = 1.6.7

        local version="1.10.2"

        asdf plugin add julia
        asdf install julia $version
        asdf global julia $version

        julia --version
    }
    main

EOF

}
main
)
