#!/bin/bash
echo install k8s tools
(
    set -exo pipefail

    sudo -u vagrant bash <<'EOF'
        set -eo pipefail ; . /etc/provision_functions ; set -x

        bashrc_add_noninteractive <<'BASHRC_EOF'
export KUBE_ENV_HOME="$HOME/.kube_env"
BASHRC_EOF

        mkdir -p "$KUBE_ENV_HOME/bin"

        version="v1.13.3"
        # version="$(curl -fsSL https://storage.googleapis.com/kubernetes-release/release/stable.txt)" # latest stable version

        mkdir -p "$KUBE_ENV_HOME/versions/$version"

        cd "$KUBE_ENV_HOME/versions/$version"

        curl -fsSL --remote-name-all https://storage.googleapis.com/kubernetes-release/release/$version/bin/linux/amd64/{kubeadm,kubelet,kubectl}

        chmod +x {kubeadm,kubelet,kubectl}

        ln -s "$KUBE_ENV_HOME/versions/$version"/{kubeadm,kubelet,kubectl} "$KUBE_ENV_HOME/bin/"

        bashrc_add_noninteractive <<'BASHRC_EOF'
export PATH="$PATH:$KUBE_ENV_HOME/bin"
BASHRC_EOF

        # Install interactive mode bash completions

        bashrc_add_interactive <<'BASHRC_EOF'
eval "$(kubeadm completion bash)"
eval "$(kubectl completion bash)"
BASHRC_EOF

EOF
)
