#!/bin/bash
echo install circleci cli
(
    set -exo pipefail

    sudo -u vagrant bash <<'EOF'
        set -eo pipefail ; . /etc/provision_functions ; set -x

        bashrc_add_noninteractive <<'BASHRC_EOF'
export CIRCLECI_HOME="$HOME/.circleci"
export PATH="$CIRCLECI_HOME/bin:$PATH"
BASHRC_EOF

        mkdir -p "$CIRCLECI_HOME/bin"

        # upstream http2 redirect broke 2019-02-12
        # curl -fsSL https://circle.ci/cli | DESTDIR="$CIRCLECI_HOME/bin" bash
        # error:
        # curl: (16) Error in the HTTP2 framing layer

        curl -fsSL https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh | DESTDIR="$CIRCLECI_HOME/bin" bash

EOF
)
