#!/bin/bash
echo install docker
(
main() {
    set -exo pipefail ; export DEBIAN_FRONTEND=noninteractive

    curl -fsSL https://get.docker.com | sudo sh -

    usermod -a -G docker vagrant

    mkdir -p /etc/services.d/dockerd
    cat <<'EOF' | install -m 0744 /dev/stdin /etc/services.d/dockerd/run
#!/bin/bash
set -exo pipefail

exec /usr/bin/dockerd
EOF
}
main
)
