#!/bin/bash
set -exo pipefail

BRANCH=$(git symbolic-ref HEAD 2>/dev/null | cut -c12-)

if [[ "$BRANCH" == "release/"* ]]; then
    if ! [[ "$BRANCH" =~ ^release\/[a-z0-9._-]+$ ]]; then
        echo 'Invalid branch name, must match regex: /^release\/[a-z0-9._-]+$/'
        exit 1
    fi
    if [[ "$BRANCH" == *"-latest" ]]; then
        echo "Invalid branch name, must not end in --latest"
        exit 1
    fi
    tag="$(printf '%s' "$BRANCH" | cut -c9-)-latest"
    git tag -d "$tag" || true
    git tag "$tag"
    git push
    git push "$(git remote show)" "$tag"
else
    git push
fi
