name: Publish Docker image on tag
on:
  push:
    tags:
      - dev-environment-latest

jobs:
  build_and_push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: pull last published docker image to populate docker cache
        run: ./scripts/pull-docker-images
      - name: build image
        run: DOCKER_BUILD_PLATFORM=linux/amd64,linux/arm64 CACHE_FROM=josephcopenhaver/docker-images:dev-environment-latest ./scripts/build "${GITHUB_SHA}"
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: push docker image
        run: |
          ./scripts/push-docker-images "${GITHUB_SHA}"
