name: Weekly Release Branch Check
on:
  schedule:
    # Every Friday at 17:30 CST with a random 1-60 minute offset (23)
    - cron: "53 22 * * 5"

jobs:
  build_dev_environment:
    name: Verify dev environment image builds without a cache
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: release/dev-environment
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: build image
        run: DOCKER_BUILD_PLATFORM=linux/amd64,linux/arm64 ./scripts/build
